AgendaTelefonica/Models/ErrorViewModel.cs
using System;

namespace AgendaTelefonica.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendaTelefonica/Controllers/EmailController.cs
using AgendaTelefonica.Core.Application.Interfaces.Services;
using AgendaTelefonica.Core.Application.ViewModels.Email;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AgendaTelefonica.Controllers
{
    public class EmailController : Controller
    {
        private readonly IEmailService _emailService;
        private readonly IUserService _userService;


        public EmailController(IEmailService emailService, IUserService userService)
        {
            _emailService = emailService;
            _userService = userService;
        }

        public async Task<IActionResult> Index(int UserId)
        {
            var getAllVm = await _emailService.GetAllViewModelWithInclude(UserId);
            var userById = await _userService.GetByIdSaveViewModel(UserId);
            ViewBag.Name = userById.Name +" "+ userById.LastName;
            
            return View(getAllVm);
        }

        //Create
        public  IActionResult Create(int UserId)
        {
            SaveEmailViewModel vm = new();
            vm.UserId = UserId;
            return View("SaveEmail", vm);
        }


        [HttpPost]
        public async Task<IActionResult> Create(SaveEmailViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("SaveEmail", vm);
            }

            await _emailService.Add(vm);

            return RedirectToRoute(new { controller = "User", action = "Index" });

        }


        public async Task<IActionResult> Delete(int id)
        {
            return View(await _emailService.GetByIdSaveViewModel(id));
        }


        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            await _emailService.Delete(id);

            return RedirectToRoute(new { controller = "User", action = "Index" });
        }

    }
}

AgendaTelefonica/Controllers/PhoneController.cs
using AgendaTelefonica.Core.Application.Interfaces.Services;
using AgendaTelefonica.Core.Application.ViewModels.Phone;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AgendaTelefonica.Controllers
{
    public class PhoneController : Controller
    {
        private readonly IPhoneService _phoneService;
        private readonly IUserService _userService;



        public PhoneController(IPhoneService phoneService, IUserService userService)
        {
            _phoneService = phoneService;
            _userService = userService;
        }


        public async Task<IActionResult> Index(int UserId)
        {
            var getAllVm = await _phoneService.GetAllViewModelWithInclude(UserId);

            var userById = await _userService.GetByIdSaveViewModel(UserId);
            ViewBag.Name = userById.Name + " " + userById.LastName;

            return View(getAllVm);
        }

        //Create
        public IActionResult Create(int UserId)
        {
            SavePhoneViewModel vm = new();
            vm.UserId = UserId;
            return View("SavePhone", vm);
        }


        [HttpPost]
        public async Task<IActionResult> Create(SavePhoneViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("SavePhone", vm);
            }

            await _phoneService.Add(vm);

            return RedirectToRoute(new { controller = "User", action = "Index" });
        }


        public async Task<IActionResult> Delete(int id)
        {
            return View(await _phoneService.GetByIdSaveViewModel(id));
        }


        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            await _phoneService.Delete(id);

            return RedirectToRoute(new { controller = "User", action = "Index" });
        }
    }
}

AgendaTelefonica/Controllers/UserController.cs
using AgendaTelefonica.Core.Application.Interfaces.Services;
using AgendaTelefonica.Core.Application.ViewModels.Email;
using AgendaTelefonica.Core.Application.ViewModels.Phone;
using AgendaTelefonica.Core.Application.ViewModels.User;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaTelefonica.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IPhoneService _phoneService;
        private readonly IEmailService _emailService;


        public UserController(IUserService userService, IPhoneService phoneService, IEmailService emailService)
        {
            _userService = userService;
            _phoneService = phoneService;
            _emailService = emailService;
        }


        public async Task<IActionResult> Index(FilterUserViewModel vm)
        {
            var contacts = await _userService.GetAllViewModelWithFilter(vm);
            var phones = await _phoneService.GetAllViewModel();
            var emails = await _emailService.GetAllViewModel();

            foreach (var contact in contacts)
            {
                contact.Phones = phones;
                contact.Emails = emails;
            }


            return View(contacts);
        }


        public IActionResult Create()
        {
            SaveUserViewModel userVm = new();
            return View("SaveUser", userVm);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SaveUserViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("SaveUser", vm);
            }

            SaveUserViewModel addUser = await _userService.Add(vm);
            if (addUser != null)
            {
                await _userService.AddUserPhone(addUser.Id, vm.Phone);
                await _userService.AddUserEmail(addUser.Id, vm.Email);
            }        

            return RedirectToRoute(new { controller = "User", action = "Index" });
        }





        public async Task<IActionResult> Edit(int id)
        {
            SaveUserViewModel vm = await _userService.GetByIdSaveViewModel(id);
            return View("SaveUser", vm);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(SaveUserViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("SaveUser", vm);
            }

            await _userService.Update(vm, vm.Id);
            return RedirectToRoute(new { controller = "User", action = "Index" });
        }




        public async Task<IActionResult> Delete(int id)
        {
            return View(await _userService.GetByIdSaveViewModel(id));
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            SaveUserViewModel contact = await _userService.GetByIdSaveViewModel(id);

            if (contact.Deleted == false)
            {
                contact.Deleted = true;
            }

            await _userService.Update(contact, id);

            return RedirectToRoute(new { controller = "User", action = "Index" });
        }
    }
}

AgendaTelefonica/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AgendaTelefonica/Views/Phone/Delete.cshtml
@using AgendaTelefonica.Core.Application.ViewModels.Phone;
@model SavePhoneViewModel
@{
    ViewData["Title"] = "Eliminar Telefono";
}


<div class="row">

    <div class="col-6 offset-3">
        <div class="card">
            <div class="card-header bg-danger text-light">
                <h4>Esta seguro que desea eliminar el numero @Model.PhoneNumber de tus contactos?</h4>
            </div>
            <div class="card-body">

                <form method="post" asp-controller="Phone" asp-action="DeletePost">

                    <input type="hidden" asp-for="Id" />

                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <a asp-controller="User" asp-action="Index" class="btn btn-warning">Cancelar</a>
                </form>

            </div>
        </div>
    </div>

</div>

AgendaTelefonica/Views/Phone/Index.cshtml
@using AgendaTelefonica.Core.Application.ViewModels.Phone;
@model List<PhoneViewModel>
@{
    ViewData["Title"] = "Phones";
}

<div class="container-fluid">

    <div class="row">

        <h2 class="display-6">Lista de Telefonos registrado por @ViewBag.Name </h2>


        @foreach (PhoneViewModel item in Model)
        {

            <div class="col-4">
                <div class="widget red-bg p-xl">
                    <h2>@item.UserName @item.UserLastName</h2>
                    <ul class="list-unstyled m-t-md">
                        
                       
                        <li>
                            <span class="fa fa-phone m-r-xs"></span>
                            <label>Contact:</label>
                            @item.PhoneNumber
                        </li>
                    </ul>
                    <div class="btn-group">
                        @if (Model.Count() != 1)
                        {
                            <a asp-controller="Phone" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-dark">Eliminar</a>
                        }
                    </div>
                </div>
            </div>
        }

    </div>

</div>

AgendaTelefonica/Views/Phone/SavePhone.cshtml
@using AgendaTelefonica.Core.Application.ViewModels.Phone;
@model SavePhoneViewModel
@{
    ViewData["Title"] = "Guardar Phone";
}


<div class="container-fluid">

    <div class="row">
        <div class="col-6 offset-3">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                <div class="card-header purple text-light">
                    <h4 class="text-center ">Añadir Telefono </h4>
                </div>
                <div class="card-body">

                    <form method="post" asp-controller="Phone" asp-action="Create">

                        <div class="mb-3">
                            <label asp-for="PhoneNumber" class="form-label">Numero de Telefono: </label>
                            <input type="tel" asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>

                        @*<input type="hidden" asp-for="Id" />*@
                        <input type="hidden" asp-for="UserId" />

                        <button type="submit" class="btn boton">Guardar</button>
                        <a asp-controller="User" asp-action="Index" class="btn btn-warning">Volver atras</a>

                    </form>

                </div>

            </div>
        </div>
    </div>

</div>

AgendaTelefonica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda Telefonica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="purple navbar navbar-expand-sm navbar-toggleable-sm   border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="User" asp-action="Index">Agenda Telefonica</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">Contactos</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AgendaTelefonica by  - <a asp-area="" asp-controller="User" asp-action="Index">Esleiker</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AgendaTelefonica/Views/User/Delete.cshtml
@using AgendaTelefonica.Core.Application.ViewModels.User;
@model SaveUserViewModel
@{
    ViewData["Title"] = "Delete Contact";
}



<div class="row">
    <div class="card text-center shadow-lg p-3 mb-5 bg-white rounded">
        <div class="col-6 offset-3">

            <div class="card-header">
                Alerta!
            </div>
            <div class="card-body">
                <form method="post" asp-controller="User" asp-action="DeletePost">
                    <input type="hidden" asp-for="Id" />

                    <h5 class="card-title">Esta seguro que desea eliminar a @Model.Name de tus contactos?</h5>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <a asp-controller="User" asp-action="Index" class="btn btn-warning">Cancelar</a>
                </form>

            </div>
        </div>

    </div>

</div>

AgendaTelefonica/Views/User/Index.cshtml
@using AgendaTelefonica.Core.Application.ViewModels.Phone
@using AgendaTelefonica.Core.Application.ViewModels.User;
@model List<UserViewModel>
@{
    ViewData["Title"] = "Users";
}


<div class="container">
    <div class="row ">


        <br />
        <div class="col-9 col-md-10 col-lg-8">
            <form class="card card-sm" class="form-inline my-2 my-lg-0" asp-controller="User" method="get">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search h4 text-body"></i>
                    </div>
                    <div class="col">
                        <input class="form-control form-control-lg form-control-borderless" ttype="search" name="Name" id="Name" aria-label="Search" placeholder="Buscar Nombre de contactos">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-lg btn-success" name="Name" value="Buscar" id="Name" type="submit">Search</button>
                        <a class="btn btn-lg btn-warning " asp-action="Index"> Ver Todos</a>

                    </div>
                </div>
            </form>
        </div>

        <div class="col-3 mt-3">
            <a asp-controller="User" asp-action="Create" class="btn boton">Agregar nuevo contacto</a>
        </div>

    </div>
</div>




@if (Model == null || Model.Count == 0)
{
    <h2 class="text-center mt-5">No se encontro ningun contacto </h2>
}
else
{

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <hr>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h1 class="text-center purple-word display-5 mt-4 mb-5">Mis Contactos</h1>
                <div class="main-box no-header clearfix">
                    <div class="main-box-body clearfix">
                        <div class="starter-template">
                        </div>
                        <div class="table-responsive">
                            <table class="table user-list">

                                <thead>
                                    <tr>
                                        <th><h4>Contacto</h4></th>
                                        <th><h4>Cedula</h4></th>
                                        <th><h4>Dirección</h4></th>
                                        <th><h4>Email</h4></th>
                                        <th><h4>Telefono</h4></th>

                                        <th><h4>Acciones</h4></th>
                                    </tr>
                                </thead>
                                @foreach (UserViewModel item in Model)
                                {
                                    <tbody>
                                        <tr>
                                            <td>
                                                <h4 class="text-primary mb-2">@item.Name  @item.LastName</h4>
                                                <div class="d-flex-column">
                                                    <p class="user-subhead text-muted">Telefonos: @item.PhonesQuantities</p>
                                                    <p class="user-subhead text-muted">Correos: @item.EmailQuantities</p>
                                                </div>

                                            </td>
                                            <td>
                                                <i class="fas fa-id-card"></i>
                                                @item.DocumentId
                                            </td>
                                            <td style="width: 10%;">
                                                <i class="fas fa-map-marker-alt"></i>
                                                <span class="label label-default">@item.Address</span>
                                            </td>
                                            <td>



                                                @foreach (var email in item.Emails)
                                                {
                                                    @if (email.UserId == item.Id)
                                                    {
                                                        <i class="fas fa-envelope"></i>
                                                        <a class="text-info text-decoration-none">@email.EmailAddress</a>
                                                        <br />
                                                    }
                                                }

                                            </td>
                                            <td>

                                                @foreach (var phone in item.Phones)
                                                {
                                                    @if (phone.UserId == item.Id)
                                                    {
                                                        <i class="fas fa-phone"></i>
                                                        <a class="text-danger text-decoration-none">@phone.PhoneNumber</a>
                                                        <br />
                                                    }
                                                }

                                            </td>

                                            <td style="width: 10%;">

                                                <div class="d-flex w-100">

                                                    <div class="m-1">

                                                        <a asp-controller="User" asp-action="Edit" asp-route-id="@item.Id" class="table-link text-info">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square fa-stack-2x"></i>
                                                                <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                                                            </span>
                                                        </a>
                                                    </div>


                                                    <div class="m-1">
                                                        <a asp-controller="User" asp-action="Delete" asp-route-id="@item.Id" class="table-link danger">
                                                            <span class="fa-stack">
                                                                <i class="fa fa-square fa-stack-2x"></i>
                                                                <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                                            </span>
                                                        </a>
                                                    </div>

                                                    <div class="m-1">

                                                        <div class="dropdown">
                                                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                Opciones
                                                            </button>
                                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                                <a asp-controller="Email" asp-action="Create" asp-route-UserId="@item.Id" class="btn btn-sm btn-outline-danger dropdown-item">Añadir Email</a>
                                                                <a asp-controller="Email" asp-action="Index" asp-route-UserId="@item.Id" class="btn btn-sm btn-outline-danger dropdown-item">Ver Correos</a>
                                                                <div class="dropdown-divider"></div>
                                                                <a asp-controller="Phone" asp-action="Create" asp-route-UserId="@item.Id" class="btn btn-sm btn-outline-danger dropdown-item">Añadir Telefono</a>
                                                                <a asp-controller="Phone" asp-action="Index" asp-route-UserId="@item.Id" class="btn btn-sm btn-outline-danger dropdown-item">Ver Telefonos</a>


                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>

                                            </td>

                                        </tr>
                                    </tbody>
                                }
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}